import { Movie } from './movie.model';

export const MOVIES: Movie[] = [
  {
    id: 1,
    title: "The Quantum Paradox",
    year: 2023,
    runtime: 148,
    genre: ["Sci-Fi", "Thriller"],
    director: "Sarah Chen",
    cast: ["Marcus Wright", "Elena Rodriguez", "James Park"],
    rating: 8.4,
    poster: "https://placehold.co/300x450/4A90E2/FFF?text=Quantum+Paradox",
    plot: "A physicist discovers a way to communicate with parallel universes, but each message sent creates catastrophic ripples across dimensions.",
    revenue: 342000000,
    budget: 85000000
  },
  {
    id: 2,
    title: "Midnight in Morocco",
    year: 2024,
    runtime: 112,
    genre: ["Romance", "Drama"],
    director: "Antoine Dubois",
    cast: ["Sofia Laurent", "Amir Hassan", "Claire Thompson"],
    rating: 7.8,
    poster: "https://placehold.co/300x450/E94B3C/FFF?text=Midnight+Morocco",
    plot: "Two strangers meet in Marrakech and embark on a whirlwind romance that challenges everything they thought they knew about love.",
    revenue: 67000000,
    budget: 22000000
  },
  {
    id: 3,
    title: "Steel Horizon",
    year: 2023,
    runtime: 135,
    genre: ["Action", "Adventure"],
    director: "David Rockwell",
    cast: ["Jake Morrison", "Yuki Tanaka", "Rachel Stone"],
    rating: 7.2,
    poster: "https://placehold.co/300x450/27AE60/FFF?text=Steel+Horizon",
    plot: "An elite team of mercenaries must stop a rogue AI from launching global nuclear strikes.",
    revenue: 456000000,
    budget: 120000000
  },
  {
    id: 4,
    title: "The Last Bookstore",
    year: 2024,
    runtime: 98,
    genre: ["Comedy", "Drama"],
    director: "Emma Walsh",
    cast: ["Tom Brennan", "Lisa Chen", "Oscar Martinez"],
    rating: 8.1,
    poster: "https://placehold.co/300x450/F39C12/FFF?text=Last+Bookstore",
    plot: "The eccentric owner of a failing bookstore brings together an unlikely group of customers who discover friendship and second chances.",
    revenue: 28000000,
    budget: 8000000
  },
  {
    id: 5,
    title: "Echoes of Thunder",
    year: 2023,
    runtime: 156,
    genre: ["Drama", "War"],
    director: "Michael Kowalski",
    cast: ["Daniel Foster", "Anna Volkov", "Samuel Jackson"],
    rating: 8.9,
    poster: "https://placehold.co/300x450/8E44AD/FFF?text=Echoes+Thunder",
    plot: "A harrowing tale of survival and brotherhood during the final days of World War II on the Eastern Front.",
    revenue: 189000000,
    budget: 65000000
  },
  {
    id: 6,
    title: "Neon Dreams",
    year: 2024,
    runtime: 105,
    genre: ["Sci-Fi", "Mystery"],
    director: "Kenji Yamamoto",
    cast: ["Alex Rivera", "Mei Lin", "Hassan Ali"],
    rating: 7.6,
    poster: "https://placehold.co/300x450/E74C3C/FFF?text=Neon+Dreams",
    plot: "In a cyberpunk future, a detective must solve murders that occur only in people's dreams.",
    revenue: 145000000,
    budget: 45000000
  },
  {
    id: 7,
    title: "The Baker's Daughter",
    year: 2024,
    runtime: 118,
    genre: ["Drama", "Family"],
    director: "Isabella Romano",
    cast: ["Marie Dubois", "Carlo Bianchi", "Sophie Laurent"],
    rating: 8.3,
    poster: "https://placehold.co/300x450/3498DB/FFF?text=Bakers+Daughter",
    plot: "A young woman returns to her family's bakery in Tuscany and rediscovers the recipes and secrets of three generations.",
    revenue: 52000000,
    budget: 15000000
  },
  {
    id: 8,
    title: "Velocity",
    year: 2023,
    runtime: 122,
    genre: ["Action", "Thriller"],
    director: "Marcus Chen",
    cast: ["Ryan Cooper", "Nina Petrov", "Lucas Wade"],
    rating: 6.9,
    poster: "https://placehold.co/300x450/16A085/FFF?text=Velocity",
    plot: "A getaway driver gets caught between rival crime syndicates in a deadly game of cat and mouse.",
    revenue: 234000000,
    budget: 55000000
  },
  {
    id: 9,
    title: "Whispers in the Wind",
    year: 2024,
    runtime: 134,
    genre: ["Horror", "Mystery"],
    director: "Patricia Blackwood",
    cast: ["Emma Stone", "Viktor Novak", "Sarah Kim"],
    rating: 7.4,
    poster: "https://placehold.co/300x450/C0392B/FFF?text=Whispers+Wind",
    plot: "A paranormal investigator travels to a remote Scottish island where an entire village vanished without a trace.",
    revenue: 98000000,
    budget: 28000000
  },
  {
    id: 10,
    title: "Cosmic Diner",
    year: 2024,
    runtime: 95,
    genre: ["Comedy", "Sci-Fi"],
    director: "Jordan Lee",
    cast: ["Chris Park", "Amanda Singh", "Tony Romano"],
    rating: 7.9,
    poster: "https://placehold.co/300x450/9B59B6/FFF?text=Cosmic+Diner",
    plot: "A 24-hour diner becomes a waystation for time travelers, aliens, and interdimensional beings.",
    revenue: 76000000,
    budget: 18000000
  },
  {
    id: 11,
    title: "The Silent Composer",
    year: 2023,
    runtime: 142,
    genre: ["Biography", "Drama"],
    director: "Helena Bergman",
    cast: ["Oscar Lindberg", "Catherine Moreau", "David Klein"],
    rating: 8.7,
    poster: "https://placehold.co/300x450/2C3E50/FFF?text=Silent+Composer",
    plot: "The untold story of a deaf composer who revolutionized classical music in 19th century Vienna.",
    revenue: 43000000,
    budget: 25000000
  },
  {
    id: 12,
    title: "Riptide",
    year: 2024,
    runtime: 108,
    genre: ["Action", "Adventure"],
    director: "Shane Mitchell",
    cast: ["Kai Johnson", "Lara Cruz", "Max Sterling"],
    rating: 7.1,
    poster: "https://placehold.co/300x450/E67E22/FFF?text=Riptide",
    plot: "A former Navy SEAL must rescue hostages from pirates in the treacherous waters of Southeast Asia.",
    revenue: 187000000,
    budget: 62000000
  },
  {
    id: 13,
    title: "Paper Lanterns",
    year: 2024,
    runtime: 126,
    genre: ["Animation", "Fantasy"],
    director: "Miyuki Tanaka",
    cast: ["Voice: Hana Sato", "Voice: Kenji Ito", "Voice: Yumi Nakamura"],
    rating: 8.6,
    poster: "https://placehold.co/300x450/1ABC9C/FFF?text=Paper+Lanterns",
    plot: "A magical tale of a girl who can bring paper creations to life and must save her village from darkness.",
    revenue: 312000000,
    budget: 75000000
  },
  {
    id: 14,
    title: "The Last Exit",
    year: 2023,
    runtime: 119,
    genre: ["Thriller", "Crime"],
    director: "Robert Hayes",
    cast: ["Vincent Drake", "Maria Gonzalez", "Thomas Wright"],
    rating: 7.5,
    poster: "https://placehold.co/300x450/34495E/FFF?text=Last+Exit",
    plot: "A desperate man takes a wrong turn on a desert highway and stumbles into a conspiracy involving a small-town sheriff.",
    revenue: 67000000,
    budget: 19000000
  },
  {
    id: 15,
    title: "Starlight Symphony",
    year: 2024,
    runtime: 140,
    genre: ["Musical", "Romance"],
    director: "Nicole Armstrong",
    cast: ["Ethan Mills", "Sophia Turner", "James Liu"],
    rating: 8.0,
    poster: "https://placehold.co/300x450/D35400/FFF?text=Starlight+Symphony",
    plot: "Two rival musicians are forced to collaborate on a Broadway show and discover an unexpected connection.",
    revenue: 156000000,
    budget: 48000000
  }
];